# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(488, 456)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.octal = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.octal.setObjectName("octal")
        self.gridLayout.addWidget(self.octal, 1, 2, 1, 1)
        self.hexadecimal = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.hexadecimal.setObjectName("hexadecimal")
        self.gridLayout.addWidget(self.hexadecimal, 3, 2, 1, 1)
        self.decimal = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.decimal.setObjectName("decimal")
        self.gridLayout.addWidget(self.decimal, 2, 2, 1, 1)
        self.binar = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.binar.setInputMask("")
        self.binar.setObjectName("binar")
        self.gridLayout.addWidget(self.binar, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.change = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.change.setObjectName("change")
        self.gridLayout.addWidget(self.change, 4, 0, 1, 1)
        self.converted = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.converted.setText("")
        self.converted.setObjectName("converted")
        self.gridLayout.addWidget(self.converted, 4, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Dwójkowy:"))
        self.label_2.setText(_translate("Dialog", "Ósemkowy:"))
        self.label_4.setText(_translate("Dialog", "Szesnastkowy:"))
        self.label_3.setText(_translate("Dialog", "Diesiętny:"))
        self.change.setText(_translate("Dialog", "Zamień"))
